server:
  data_dir: data
  state_file: server_state.json
  api_port: 18080
  web_port: 15173
bot:
  timer_interval: 120
plugin:
  pip_mirror: https://pypi.tuna.tsinghua.edu.cn/simple
update:
  repo: Dresteam/MisMiss
  mirror: ""
  proxy: ""
logging:
  dir: logs
  level: DEBUG
